//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Modules.WeBlog.Layouts {
	
	
	public partial class BlogLayout {
		
		protected System.Web.UI.HtmlControls.HtmlForm mainform;
	}
}
